import { RecentOrderProps } from "@/interface/index";

export const RecentOrder: RecentOrderProps[] = [
  {
    order_id: "a1b2c3d4",
    product_name: "Laptop",
    order_items: 2,
    amount: 100,
    date: new Date("2024-07-16"),
    status: "shipped",
    email: "m@example.com",
  },
  {
    order_id: "e5f6g7h8",
    order_items: 1,
    product_name: "Iphone",
    date: new Date("2024-10-20"),
    amount: 125,
    status: "delivered",
    email: "example@gmail.com",
  },
  {
    order_id: "i9j0k1l2",
    order_items: 1,
    product_name: "Leather Straps Wristwatch",
    date: new Date("2024-10-21"),
    amount: 120,
    status: "cancelled",
    email: "example@gmail.com",
  },
  {
    order_id: "m3n4o5p6",
    order_items: 1,
    product_name: "Steel Analog Couple Watches",
    date: new Date("2024-10-22"),
    amount: 35,
    status: "returned",
    email: "example@gmail.com",
  },
  {
    order_id: "q7r8s9t0",
    order_items: 1,
    product_name: "Fashion Magnetic Wrist Watch",
    date: new Date("2024-10-23"),
    amount: 130,
    status: "shipped",
    email: "example@gmail.com",
  },
  {
    order_id: "u1v2w3x4",
    order_items: 1,
    product_name: "Mens Casual Premium Slim Fit T-Shirts",
    date: new Date("2024-10-24"),
    amount: 140,
    status: "delivered",
    email: "example@gmail.com",
  },
  {
    order_id: "y5z6a7b8",
    order_items: 1,
    product_name: "Mens Cotton Jacket",
    date: new Date("2024-10-25"),
    amount: 150,
    status: "cancelled",
    email: "example@gmail.com",
  },
  {
    order_id: "c9d0e1f2",
    order_items: 1,
    product_name: "Mens Casual Slim Fit",
    date: new Date("2024-10-26"),
    amount: 160,
    status: "returned",
    email: "example@gmail.com",
  },
  {
    order_id: "c9d0e1f2",
    order_items: 1,
    product_name: "White Gold Plated Princess",
    date: new Date("2024-11-5"),
    amount: 200,
    status: "delivered",
    email: "example@gmail.com",
  },
];
