import { ProductDataProps } from "@/interface/index";

export const ProductData: ProductDataProps[] = [
  {
    order_id: "a1b2c3d4",
    product_name: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    order_items: 2,
    amount: 100,
    category: "men's clothing",
    date: new Date("2024-07-16"),
    status: "shipped",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "e5f6g7h8",
    order_items: 1,
    product_name: "Mens Casual Premium Slim Fit T-Shirts",
    date: new Date("2024-10-20"),
    amount: 125,
    category: "men's clothing",
    phone: "8899562237",
    status: "delivered",
    image:
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "i9j0k1l2",
    order_items: 1,
    product_name: "Mens Cotton Jacket",
    date: new Date("2024-10-21"),
    amount: 950,
    status: "cancelled",
    category: "men's clothing",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "m3n4o5p6",
    order_items: 1,
    product_name: "Mens Casual Slim Fit",
    date: new Date("2024-10-22"),
    amount: 35,
    status: "returned",
    category: "men's clothing",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "q7r8s9t0",
    order_items: 1,
    product_name: "Solid Gold Petite Micropave",
    date: new Date("2024-10-23"),
    amount: 130,
    status: "shipped",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    phone: "8899562237",
    email: "example@gmail.com",
  },
  {
    order_id: "u1v2w3x4",
    order_items: 1,
    product_name: "White Gold Plated Princess",
    date: new Date("2024-10-24"),
    amount: 140,
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    status: "delivered",
    phone: "8899562237",
    email: "example@gmail.com",
  },
  {
    order_id: "y5z6a7b8",
    order_items: 1,
    product_name: "Pierced Owl Rose Gold Plated Stainless Steel Double",
    date: new Date("2024-10-25"),
    amount: 150,
    status: "cancelled",
    category: "jewelery",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "c9d0e1f2",
    order_items: 1,
    product_name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    date: new Date("2024-10-26"),
    amount: 160,
    status: "returned",
    category: "electronics",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "c9d0e1f2",
    order_items: 1,
    product_name:
      "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    date: new Date("2024-11-5"),
    amount: 200,
    status: "delivered",
    category: "electronics",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    email: "example@gmail.com",
  },
  {
    order_id: "c9d0e1gh2",
    order_items: 1,
    product_name:
      "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    date: new Date("2024-11-5"),
    amount: 200,
    status: "delivered",
    category: "electronics",
    phone: "8899562237",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    email: "example@gmail.com",
  },
];
